name: build samp
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - yolks/samp/**
jobs:
  push:
    name: "yolks:${{ matrix.build }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - samp
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./yolks/${{ matrix.build }}
          file: ./yolks/${{ matrix.build }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/daniscript18/yolks:${{ matrix.build }}